### PR TITLE
implemented Source Link 

### LINKED ISSUE #6: Enable Source Link for easier debugging
### Expected  behavior

Press F11 to step into code and debug the code

### Actual behavior

because no source info are found in the provided PDB, debugger steps over

### Solution: 

[enable Source Link](https://github.com/dotnet/sourcelink#using-sourcelink) to [fetch the source from github](https://github.com/dotnet/designs/blob/master/accepted/diagnostics/source-link.md#source-link-file-specification) during debugging to be able to step into the code.

### PR DESCRIPTION
**Pull request by MagicAndre1981**
fixes https://github.com/LorenzCK/WindowsFormsAero/issues/6

### CODE REVIEW

**Comment by LorenzCK** [comment]
Neat, thanks! 👏

**Comment by MagicAndre1981** [comment]
ok, can you please upload this as new nuget package 3.1.1 or 3.2 so that I can ditch the checkedin code from my repositories and switch to NuGet packages?

**Comment by LorenzCK** [comment]
Sorry for the delay, I had no access to the dev machine with Visual Studio until now. [Version 3.1.1](https://www.nuget.org/packages/Windows-Forms-Aero/3.1.1) has been uploaded, should be online soon.

**Comment by MagicAndre1981** [comment]
thanks, 3.1.1 works fine and I can step into the code during debugging when VS downloads the .cs files 😍 👍

**Comment by LorenzCK** [comment]
Great! 😉

**Pull request merged**
